# -*- coding: utf-8 -*-
"""Modin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zz46Cvy820IjLOGsLSjRH5_6Du2kDNIw
"""

!pip install modin[ray]
!pip install -U ipykernel

file_name = "/content/drive/My Drive/Colab Notebooks/worldcitiespop.csv"

file_name

import os
print ("Size of file is {} MB".format(os.path.getsize(file_name) >> 20))

import time
import numpy as np
import pandas as pd
import modin.pandas as md

s = time.time()
df_pandas = pd.read_csv(file_name)
e = time.time()
print("Pandas Loading Time = {}".format(e-s))

s = time.time()
df_modin = md.read_csv(file_name)
e = time.time()
print("Modin Loading Time = {}".format(e-s))

s = time.time()
df_pandas_concat = pd.concat([df_pandas for _ in range(5)])
e = time.time()
print("Pandas Concat Time = {}".format(e-s))

s = time.time()
df_modin_concat = md.concat([df_modin for _ in range(5)])
e = time.time()
print("Modin Concat Time = {}".format(e-s))

s = time.time()
t_pandas = df_pandas_concat.isnull()
e = time.time()
print("Pandas Null Time Check = {}".format(e-s))

s = time.time()
t_modin = df_modin_concat.isnull()
e = time.time()
print("Modin Null Time Check = {}".format(e-s))

s = time.time()
max_pandas = df_pandas_concat["Population"].max()
e = time.time()
print ("Max value in Pandas Dataframe = {}".format(max_pandas))
print("Pandas Count Time = {}".format(e-s))

s = time.time()
max_modin = df_modin_concat["Population"].max()
e = time.time()
print ("Max value in Modin Dataframe = {}".format(max_modin))
print("Modin Count Time = {}".format(e-s))